#!/bin/bash

source ${OPENSHIFT_PYTHON_DIR}/virtenv/bin/activate

echo "Executing 'cd $OPENSHIFT_REPO_DIR/wsgi/webconfgen/'"
cd "$OPENSHIFT_REPO_DIR/wsgi/webconfgen/"

echo "Executing 'python $OPENSHIFT_REPO_DIR/wsgi/webconfgen/manage.py makemigrations --noinput'"
python "$OPENSHIFT_REPO_DIR"wsgi/webconfgen/manage.py makemigrations --noinput

echo "Executing 'python $OPENSHIFT_REPO_DIR/wsgi/webconfgen/manage.py migrate --noinput'"
python "$OPENSHIFT_REPO_DIR"wsgi/webconfgen/manage.py migrate --noinput

echo "Executing 'python $OPENSHIFT_REPO_DIR/wsgi/webconfgen/manage.py test --noinput'"
python "$OPENSHIFT_REPO_DIR"wsgi/webconfgen/manage.py test --noinput
