#!/bin/bash

source ${OPENSHIFT_PYTHON_DIR}/virtenv/bin/activate

echo "Executing 'python $OPENSHIFT_REPO_DIR/wsgi/webconfgen/manage.py migrate --noinput'"
python "$OPENSHIFT_REPO_DIR"wsgi/webconfgen/manage.py migrate --noinput

echo "Executing 'python $OPENSHIFT_REPO_DIR/wsgi/webconfgen/manage.py collectstatic --noinput'"
python "$OPENSHIFT_REPO_DIR"wsgi/webconfgen/manage.py collectstatic --noinput
